[workspace]
resolver = "3"
members = [
    "crates/northrend",
    "crates/northrend-assets",
    "crates/northrend-backend",
    "crates/northrend-game",
    "crates/northrend-input",
    "crates/northrend-math",
    "crates/northrend-render",
    "crates/northrend-wgpu",
    "crates/northrend-winit",
    "crates/northrend-world",
]

[workspace.package]
version = "0.0.1"
edition = "2024"
authors = ["Carnivohra <carnivohra@gmail.com>"]
license = "MPL-2.0"

[workspace.dependencies]
bytemuck = "1.25.2"
flate2 = { version = "1.1.9", default-features = false, features = ["zlib-rs"] }
raw-window-handle = "0.6.2"
pollster = "1.0.1"
thiserror = "2.0.20"
winit = "0.30.13"
wgpu = "30.0.0"
