[package]
name = "northrend"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
northrend-backend = { path = "../northrend-backend" }
northrend-game = { path = "../northrend-game" }
northrend-render = { path = "../northrend-render" }

pollster = { workspace = true }
