[package]
name = "northrend-render"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
northrend-backend = { path = "../northrend-backend" }
northrend-math = { path = "../northrend-math" }
northrend-world = { path = "../northrend-world" }
